# Generated by Django 3.2.8 on 2021-11-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gameName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
