# Generated by Django 3.2.8 on 2021-12-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_gamename'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='health',
            field=models.IntegerField(default='100'),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default='0'),
        ),
    ]
